module.exports = {
  // "Activity"        : require('./components/icons/magneto/Activity.js'),
  // "Camera"          : require('./components/icons/magneto/Camera.js'),
  // "Check"           : require('./components/icons/magneto/Check.js'),
  // "Edit"            : require('./components/icons/magneto/Edit.js'),
  // "Trash"           : require('./components/icons/magneto/Trash.js'),
  // "TripleArrowRight": require('./components/icons/magneto/TripleArrowRight.js'),
  // "ThreeDots"       : require('./components/icons/magneto/ThreeDots.js'),
  // "Language"        : require('./components/icons/magneto/Language.js'),
  // "Education"       : require('./components/icons/magneto/Education.js'),
  // "Experience"      : require('./components/icons/magneto/Experience.js'),
  // "Skill"           : require('./components/icons/magneto/Skill.js'),
  // "Info"            : require('./components/icons/magneto/Info.js'),
  // "Contact"         : require('./components/icons/magneto/Contact.js'),
  // "Note"            : require('./components/icons/magneto/Note.js'),
  // "Network"         : require('./components/icons/magneto/Network.js'),
  // "Calendar"        : require('./components/icons/magneto/Calendar.js'),
  // "Calendar_2"      : require('./components/icons/magneto/Calendar-2.js'),
  // "Location"        : require('./components/icons/magneto/Location.js'),
  // "Salary"          : require('./components/icons/magneto/Salary.js'),
  // "Money"           : require('./components/icons/magneto/Money.js'),
  // "Filter"          : require('./components/icons/magneto/Filter.js'),
  // "CarretDown"      : require('./components/icons/magneto/CarretDown.js'),
  // "DoubleArrowDown" : require('./components/icons/magneto/DoubleArrowDown.js'),
  // "Download"        : require('./components/icons/magneto/Download.js'),
  // "Fullbody"        : require('./components/icons/magneto/Fullbody.js'),
  // "EmojiBad"        : require('./components/icons/magneto/EmojiBad.js'),
  // "EmojiNormal"     : require('./components/icons/magneto/EmojiNormal.js'),
  // "EmojiGood"       : require('./components/icons/magneto/EmojiGood.js'),
  // "EmojiReallyBad"  : require('./components/icons/magneto/EmojiReallyBad.js'),
  // "EmojiGreat"      : require('./components/icons/magneto/EmojiGreat.js'),
  // "Evaluate"        : require('./components/icons/magneto/Evaluate.js'),
  // "Star"            : require('./components/icons/magneto/Star.js'),
  // "Exclamation"            : require('./components/icons/magneto/Exclamation.js')
};
